services:
  - docker

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - docker build --tag unifem/openfoam-ccx . && docker push unifem/openfoam-ccx && curl -X POST https://registry.hub.docker.com/u/unifem/openfoam-ccx/trigger/$DOCKER_TOKEN/
  - docker images
