os: linux
dist: trusty
language: python
services: docker
sudo: false

env:
  global:
    - BASE=unifem/mapper-desktop:latest

before_script:
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - docker pull $BASE

script:
  - 'docker build --tag unifem/openfoam-ccx . && 
     docker push unifem/openfoam-ccx'
  - docker images
