services:
  - docker

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - docker build --tag multiphysics/openfoam-ccx . && docker push multiphysics/openfoam-ccx
  - docker images
